version: '2'
services:
  catalog-service:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.service
    ports:
      - "8080:8080"
  db:
    build:
      context: ./docker
      dockerfile: Dockerfile.postgres
    ports:
      - "6789:5432"
    env_file:
      - .env
    volumes:
      - ./data/postgres:/var/lib/postgresql